#' Synthetic PBMC-like single-cell example data
#'
#' A deterministic, synthetic embedding with common single-cell visualization
#' semantics. It is intended only for package examples and does not represent
#' biological measurements.
#'
#' @format A data frame with 720 rows and 12 variables:
#' \describe{
#'   \item{cell_id}{Unique synthetic cell identifier.}
#'   \item{UMAP1, UMAP2}{Synthetic two-dimensional embedding coordinates.}
#'   \item{cell_type}{Six cell-identity factor levels.}
#'   \item{lineage}{Lymphoid or myeloid parent lineage.}
#'   \item{sample}{Four sample factor levels.}
#'   \item{condition}{Control or stimulated condition.}
#'   \item{MS4A1}{Synthetic non-negative expression for a B-cell marker.}
#'   \item{signed_score}{Synthetic score centered around zero.}
#'   \item{pseudotime}{Synthetic trajectory value in `[0, 1]`.}
#'   \item{percent_mito}{Synthetic mitochondrial-read percentage.}
#'   \item{n_counts}{Synthetic library-size count.}
#' }
#' @source Generated by `data-raw/build-example-data.R`.
#' @examples
#' data(sc_example)
#' head(sc_example)
"sc_example"
